version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: lab1-postgres
    environment:
      POSTGRES_USER: snowflake
      POSTGRES_PASSWORD: snowflake
      POSTGRES_DB: snowflake
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/data:ro
      - ./ddl/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./dml/load_data.sql:/docker-entrypoint-initdb.d/2_load_data.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U snowflake -d snowflake"]
      interval: 5s
      timeout: 5s
      retries: 10

  spark:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: lab1-spark
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dml/spark_etl.py:/app/spark_etl.py
      - ./jars/postgresql-42.7.3.jar:/app/postgresql-jdbc.jar
    command: ["/bin/bash", "-c", "until nc -z postgres 5432; do echo 'Waiting for PostgreSQL...'; sleep 1; done; sleep 5; /opt/bitnami/spark/bin/spark-submit --master local[*] --jars /app/postgresql-jdbc.jar --driver-class-path /app/postgresql-jdbc.jar /app/spark_etl.py"]    
    